---
title:
  en: Last news from François
  fr: Les nouvelles de François

description:
  en: Last bist from François Scala.
  fr: Les dernières nouvelles de François Scala.

baseurl: ""
url: ""
email: blog@arcenik.met

index:
  en:
  fr: accueil.html

feed:
  en: /feed.xml
  fr: /flux.xml

twitter_username: arcenik
github_username:  arcenik

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include:
  - "_images"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
